### ISSUE TITLE
Overlapping statusbar

### ISSUE THREAD

**Issue by schnittstabil** [dempfi/ayu#19] opened 2016-10-06 20:44 UTC
The status bar is overlapping on Linux, ST Build 3126:
![status-bar](https://cloud.githubusercontent.com/assets/6059032/19169641/a4f67240-8c15-11e6-8b56-070fc506b241.png)

Maybe related to #4?

Awesome theme, btw.

**Comment by dempfi** [comment] 2016-10-07 08:35
Duplicate of https://github.com/dempfi/ayu/issues/12

**Closed by dempfi** 2016-10-07 08:35 UTC
