### ISSUE TITLE
wrong graphic with advanced new file plugin

### ISSUE THREAD

**Issue by crapthings** [dempfi/ayu#62] opened 2016-11-14 02:34 UTC
it looks like statusbar cut the advnaced new file input box

<img width="1918" alt="screen shot 2016-11-14 at 10 34 04" src="https://cloud.githubusercontent.com/assets/1147704/20251657/ea51f662-aa55-11e6-9fa9-8d58f166994a.png">

**Comment by dempfi** [comment] 2016-11-14 06:49
Duplicate of https://github.com/dempfi/ayu/issues/12

**Closed by dempfi** 2016-11-14 06:49 UTC

**Comment by crapthings** [comment] 2016-11-14 06:56
cool~
