### ISSUE TITLE
Tiny scrollbar at bottom

### ISSUE THREAD

**Issue by Sensiblemnd** [dempfi/ayu#55] opened 2016-11-04 14:42 UTC
This theme is excellent but the scrollbar tend to be super tiny and unusable.  How can it be fixed?

![screenshot 7](https://cloud.githubusercontent.com/assets/940303/20009550/4fc1fb24-a27b-11e6-9a3f-5a31711b1f14.png)

**Comment by dempfi** [comment] 2016-11-04 16:11
I will add option for wider scrollbars soon, but this issue is duplicate of https://github.com/dempfi/ayu/issues/15

**Closed by dempfi** 2016-11-04 16:11 UTC
