### ISSUE TITLE
Side Bar bug

### ISSUE THREAD

**Issue by bumTomica** [dempfi/ayu#17] opened 2016-10-06 16:47 UTC
Open files (or Folders when Open files are disabled) are overlapping with menu bar on Linux. Same when menu bar is hidden.

[![sidebar-bug.png](https://s14.postimg.org/jrc2ghnj5/sidebar_bug.png)](https://postimg.org/image/sz4ax6ul9/)

**Comment by dempfi** [comment] 2016-10-06 17:53
duplicate of https://github.com/dempfi/ayu/issues/4, let's move discussion to there

**Closed by dempfi** 2016-10-06 17:53 UTC
