### ISSUE TITLE
How to remove OS X border/menu-bar

### ISSUE THREAD

**Issue by frdmn** [dempfi/ayu#34] opened 2016-10-10 13:33 UTC
How did you get rid of the grey OS X menu bar?

Here's how it looks for me right now:

![bildschirmfoto 2016-10-10 um 15 20 11](https://cloud.githubusercontent.com/assets/944459/19237803/f2c10512-8efe-11e6-84a4-e05687d61f45.png)

**Comment by dempfi** [comment] 2016-10-10 18:13
Duplicate of https://github.com/dempfi/ayu/issues/8.
To;tr no way to remove, it's just a crenndshot without a title bar.

**Closed by dempfi** 2016-10-10 18:13 UTC
