### ISSUE TITLE
Ayu is overlapping AdvancedNewFile

### ISSUE THREAD

**Issue by k15a** [dempfi/ayu#48] opened 2016-10-19 18:26 UTC
Hey,

I just noticed that Ayu is overlapping the [Advanced​New​File](https://packagecontrol.io/packages/AdvancedNewFile) dialog. I think it's a problem with Ayu because with the default theme AdvancedNewFile is not hidden. If that's not a problem with Ayu I am happy to file an issue at AdvancedNewFile

![bildschirmfoto 2016-10-19 um 20 19 42](https://cloud.githubusercontent.com/assets/20357450/19531856/80cec9f2-9639-11e6-86e6-413ed30f8bc0.jpg)

**Comment by dempfi** [comment] 2016-10-19 19:14
This is a duplicate of https://github.com/dempfi/ayu/issues/42

**Closed by dempfi** 2016-10-19 19:14 UTC
Labels: duplicate
