### ISSUE TITLE
File rename pallette is obscured

### ISSUE THREAD

**Issue by remy** [dempfi/ayu#72] opened 2016-11-27 18:04 UTC
<img width="552" alt="screen shot 2016-11-27 at 17 47 24" src="https://cloud.githubusercontent.com/assets/13700/20650570/aa33c7da-b4c9-11e6-8267-53ab2bd17ca5.png">

I wasn't sure of it's name, but I'm using the latest (I think) Ayu, I have my font size set to 21 (yeah, I know!) - I wasn't sure if it was a factor, but when I set the font size to 12, the line is readable (but the font, to me, is super small).

**Comment by dempfi** [comment] 2016-11-27 18:07
Duplicate of https://github.com/dempfi/ayu/issues/12

**Closed by dempfi** 2016-11-27 18:07 UTC

**Comment by remy** [comment] 2016-11-27 18:19
@dempfi thank you! I did search open issues, but didn't think to search the closed issues. Fixed now I dragged the sublime splitter. Ta again.

**Comment by k15a** [comment] 2016-11-27 18:38
@dempfi Do you know how to reproduce this after it's fixed? I would like to make a gif and add it to the readme.
